codecov:
  require_ci_to_pass: yes
  # Token is provided via GitHub Actions workflow (secrets.CODECOV_TOKEN)

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        # PRs that decrease coverage below 100% will fail
    patch:
      default:
        target: 100%
        # All new/changed code must be covered
    changes:
      default:
        target: 100%
        # Coverage changes must maintain 100%

comment:
  layout: "reach,diff,flags,files"
  behavior: always
  require_changes: true
  # Always comment on PRs with coverage information

# Files excluded from coverage requirements
# See COVERAGE.md for policy details
ignore:
  - "ffi/**/*"              # FFI wrapper code
  - "**/generated/**"       # Any generated directories
  - "schema/**/*"           # Schema definition files
  - "**/build.rs"           # Build scripts
